<?php
/**
 * @var \Magento\Braintree\Block\Hic\CartTestData $block
 */

 $styleConfig = [
    'buttonColorTestEnabled' => $block->isPaypalButtonColorTestEnabled(),
    'buttonShapeTestEnabled' => $block->isPaypalButtonShapeTestEnabled()
 ];

 $config = [
     'paypalExpress' => array_merge([
        'testEnabled' => $block->isPaypalExpressTestEnabled(),
        'disabled' => $block->isPaypalExpressDisabled()
     ], $styleConfig),
     'paypalCredit' => array_merge([
        'testEnabled' => $block->isPaypalCreditTestEnabled(),
        'disabled' => $block->isPaypalCreditDisabled()
     ], $styleConfig),
     'applePay' => [
        'testEnabled' => $block->isApplePayTestEnabled(),
        'disabled' => $block->isApplePayDisabled()
     ],
     'googlePay' => [
        'testEnabled' => $block->isGooglePayTestEnabled(),
        'disabled' => $block->isGooglePayDisabled()
     ]
 ];

    ?>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Braintree/js/hic/cart-tests": <?php /* @noEscape */ echo json_encode($config); ?>
    }
}
</script>
