<?php
/**
 * @var \Magento\Braintree\Block\Hic\CartTests $block
 */

 $config = [
     'paypalExpressState' => $block->getPaypalExpressState(),
     'paypalCreditState' => $block->getPaypalCreditState(),
     'applePayState' => $block->getApplePayState(),
     'googlePayState' => $block->getGooglePayState()
];

?>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Braintree/js/hic/cart-tests": <?php /* @noEscape */ echo json_encode($config); ?>
    }
}
</script>