<?php
/**
 * @var \Magento\Braintree\Block\Hic\MiniCartTestData $block
 */

$config = [
    'paypalExpress' => [
      'testEnabled' => $block->isPaypalExpressTestEnabled(),
      'disabled' => $block->isPaypalExpressDisabled()
    ],
    'paypalCredit' => [
       'testEnabled' => $block->isPaypalCreditTestEnabled(),
       'disabled' => $block->isPaypalCreditDisabled()
    ],
    'applePay' => [
       'testEnabled' => $block->isApplePayTestEnabled(),
       'disabled' => $block->isApplePayDisabled()
    ],
    'googlePay' => [
       'testEnabled' => $block->isGooglePayTestEnabled(),
       'disabled' => $block->isGooglePayDisabled()
    ]
];


?>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Braintree/js/hic/minicart-tests": <?php /* @noEscape */ echo json_encode($config); ?>
    }
}
</script>